export const USER_DATA_REQUEST = 'USER_DATA_REQUEST';
export const USER_DATA_SUCCESS = 'USER_DATA_SUCCESS';
export const USER_DATA_ERROR = 'USER_DATA_ERROR';

export const ALBUM_DATA_REQUEST = 'ALBUM_DATA_REQUEST';
export const ALBUM_DATA_SUCCESS = 'ALBUM_DATA_SUCCESS';
export const ALBUM_DATA_ERROR = 'ALBUM_DATA_ERROR';
